package com.proctoring.backend.model.incident;

public enum IncidentType {

    FACE_NOT_DETECTED,
    MULTIPLE_FACES_DETECTED,
    EYES_CLOSED,
    LOOKING_AWAY,
    PHONE_DETECTED,
    SPEAKING_DETECTED,

    TAB_SWITCH,
    WINDOW_BLUR,
    FULLSCREEN_EXIT,

    SESSION_TIMEOUT,
    SESSION_AUTO_SUSPEND,

    PROCTOR_SUSPENDED_SESSION,
    PROCTOR_RESUMED_SESSION,
    PROCTOR_ENDED_SESSION
}